import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

const root = join(import.meta.dir, "..");
const schemaPath = join(root, "schemas", "package-v2.schema.json");
const generatedPath = join(root, "tools", "generated", "package-v2-validator.js");
const cachePath = join(root, ".bun-cache", "package-v2-validator.raw.mjs");

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  code: { esm: true, lines: true, source: true },
});
const validate = ajv.compile(schema);
const rawCode = standaloneCode(ajv, validate);

mkdirSync(dirname(cachePath), { recursive: true });
writeFileSync(cachePath, rawCode, "utf8");

const build = await Bun.build({
  entrypoints: [cachePath],
  format: "esm",
  minify: false,
  target: "bun",
});
if (!build.success || build.outputs.length !== 1) {
  const detail = build.logs.map((entry) => entry.message).join("; ");
  throw new Error(`could not bundle package-v2 validator${detail ? `: ${detail}` : ""}`);
}

const bundled = await build.outputs[0]!.text();
const output = `// Generated by tools/generate-package-validator.ts. Do not edit.\n${bundled}`;

if (process.argv.includes("--check")) {
  if (!existsSync(generatedPath) || readFileSync(generatedPath, "utf8") !== output) {
    throw new Error("generated package-v2 validator is stale; run bun run generate:schema");
  }
} else {
  mkdirSync(dirname(generatedPath), { recursive: true });
  writeFileSync(generatedPath, output, "utf8");
}
